openapi: 3.0.3
info: 
  title: Character Cubby API
  version: 1.0.0
paths: 
  /users:
    post: 
      tags:
        - Users
      summary: Create a new user account
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required:
               - username
               - email
               - password
               - pronouns
              properties:
               username: 
                type: string
               email: 
                type: string
               password: 
                type: string
                format: password
               pronouns: 
                type: string
               profile picture: 
                type: string
                format: byte
               about me: 
                type: string
            example:
              username: JellyCat
              email: JellyCats89@gmail.com
              password: jumpingjellybeans8!
              pronouns: She/Her
              profile picture: image.png
              about me: smol bean who likes cats
      responses:
        201: 
          description: User sucessfully created
        400:
          description: Request body not correctly formatted
  /users/{user_id}:
    parameters: 
        - name: user_id
          in: path
          required: true
          schema:
            type: string
    delete:
      tags:
       - Users
      summary: Delete a user
      responses:
        204: 
          description: Successfully deleted a user
components:
  schemas:
    Template:
      type: object
      properties:
        user id:
          type: string
          readOnly: true
        description: 
          type: string
        permissions: 
          type: string
        fields:
          type: array
          items: 
            type: object
              properties: 
                - Name
                - Information
        
        
          
          
          
          
          