openapi: 3.0.3
info: 
  title: Character Cubby API
  version: 1.0.0
paths: 
  /users:
    post: 
      tags:
        - Users
      summary: Create a new user account
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/User'
            example:
              username: JellyCat
              email: JellyCats89@gmail.com
              password: jumpingjellybeans8!
              pronouns: She/Her
              profile picture: image.png
              about me: smol bean who likes cats
      responses:
        201: 
          description: User sucessfully created
        400:
          description: Request body not correctly formatted
        409:
          description: User already exists
  /users/{user_id}:
    parameters: 
        - name: user_id
          in: path
          required: true
          schema:
            type: string
    delete:
      tags:
       - Users
      summary: Delete a user
      responses:
        204: 
          description: Successfully deleted a user
    put:
      tags:
       - Users
      summary: Update a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              username: JellyCat
              email: JellyCats89@gmail.com
              password: jumpingjellybeans8!
              pronouns: She/Her
              profile picture: image.png
              about me: smol bean who likes cats
      responses:
        200:
          description: Sucessfully updated a user
        400:
          description: Request body not correctly formatted
    get:
      tags:
         - Users
      summary: Retrieve a user
      responses:
        200:
          description: Successfully retrieved a user
        400:
          description: Incorrectly formatted request
  /users/{user_id}/login:
    parameters: 
        - name: user_id
          in: path
          required: true
          schema:
            type: string
    put:
      tags:
       - Users
      summary: Log in a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
               - password
              properties:
                password:
                  type: string
                  format: password
            example:
              password: jumpingjellybeans8!
      responses:
        200: 
          description: Authenticated
        400:
          description: Invalid request
        403:
          description: Access denied
  /users/{user_id}/logout:
    parameters: 
        - name: user_id
          in: path
          required: true
          schema:
            type: string
    put:
      tags:
       - Users
      summary: Log out a user.
      responses:
        200: 
          description: Logged out.
        403:
          description: Access denied
  /templates:
    post: 
      tags:
        - Templates
      summary: Create a new template
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/Template'
            example:
              user id: 237e9877-e79b-12d4-a765-321741963000
              name: Fluttercats
              description: Fluttercats are a special species of fae found near quiet cottages and gardens. Shy and secretive, these little fae only tend to come out at night. Ranging from four to six inches at the shoulder, Fluttercats have butterfly wings that come in most ever color that always match their eyes.
              permissions: Public
              fields: 
                 - Pronouns:
                     - string
                 - Wing Type:
                     - string
                 - Coat Pattern:
                     - string
                 - Height at Shoulder:
                     - double
                 - Description:
                     - string
                 - Personality:
                     - string
      responses:
        201: 
          description: Template sucessfully created
        400:
          description: Request body not correctly formatted
  /templates/{template_id}/{user_id}:
    parameters: 
        - name: template_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
    delete:
      tags:
       - Templates
      summary: Delete a template
      responses:
        204: 
          description: Successfully deleted a template
    put:
      tags:
       - Templates
      summary: Update a template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
            example:
              name: Fluttercats
              description: Fluttercats are a special species of fae found near quiet cottages and gardens. Shy and secretive, these little fae only tend to come out at night. Ranging from four to six inches at the shoulder, Fluttercats have butterfly wings that come in most ever color that always match their eyes.
              permissions: Public
              fields: 
                 - Pronouns:
                     - string
                 - Wing Type:
                     - string
                 - Coat Pattern:
                     - string
                 - Height at Shoulder:
                     - double
                 - Description:
                     - string
                 - Personality:
                     - string
      responses:
        200:
          description: Sucessfully updated a template
        400:
          description: Request body not correctly formatted
    get:
      tags:
         - Templates
      summary: Retrieve a template
      responses:
        200:
          description: Successfully retrieved a template
        400:
          description: Incorrectly formatted request
components:
  schemas:
    User:
      type: object
      required:
       - username
       - email
       - password
       - pronouns
      properties:
        username: 
          type: string
        email: 
          type: string
        password: 
          type: string
          format: password
        pronouns: 
          type: string
        profile picture: 
          type: string
          format: byte
        about me: 
          type: string
    Template:
      type: object
      properties:
        user id:
          type: string
          readOnly: true
        name: 
          type: string
        description: 
          type: string
        permissions: 
          type: string
        fields:
          type: array
          items: 
            type: object
            properties: 
                field name:
                  type: string
                information:
                  type: string
    Character:
      type: object
      properties:
        user id:
          type: string
          readOnly: true
        template id:
          type: string
          readOnly: true
        name: 
          type: string
        information:
          type: array
          items: 
            type: object
            properties: 
                field name:
                  type: string
                information:
                  type: string
        
          
          
          
          
          